language: r
dist: xenial
cache: packages
branches:
    only:
        - master
r_packages:
    - tidyverse
    - mgcViz
    - devtools
    - microbenchmark
    - gamair
    - tweedie
    - Rcpp
    - RcppArmadillo
    - RcppParallel
    - mvtnorm
    - hexbin
    - sitmo

r_github_packages:
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'

before_deploy:
    - rm public/.gitignore
    
# Some libraries need to be installed, otheriwse rgl install fails
addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev    
    
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
    local_dir: public
    target_branch: gh-pages
